name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: '${{ github.workflow }}-${{ !contains(github.event.pull_request.labels.*.name, ''ci-test-flaky'') && github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Chrome + sandbox helper
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends google-chrome-stable
          # copy helper to a generic path and fix its perms
          sudo cp /opt/google/chrome/chrome-sandbox /usr/local/sbin/chrome-devel-sandbox
          sudo chown root:root /usr/local/sbin/chrome-devel-sandbox
          sudo chmod 4755      /usr/local/sbin/chrome-devel-sandbox
          echo "CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox" >> "$GITHUB_ENV"
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install npm dependencies
        run: npm ci
      - name: Build and test
        run: npm run ci-check
