name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
        with:
          just-version: 1.25.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: just build
      - name: Set wrangler version
        id: wrangler
        run: echo "version=$(jq -r .devDependencies.wrangler packages/cf/package.json)" >> "$GITHUB_OUTPUT"
      - name: Deploy
        uses: cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ steps.wrangler.outputs.version }}
          workingDirectory: 'packages/cf'
          command: pages deploy --project-name bitextual-pages --commit-dirty=true ../web/dist
